import makeWASocket, {
  DisconnectReason,
  fetchLatestBaileysVersion,
  makeCacheableSignalKeyStore,
  useMultiFileAuthState,
  Browsers,
  jidNormalizedUser
} from 'baileys'
import { Boom } from '@hapi/boom'
import qrcode from 'qrcode-terminal'
import NodeCache from 'node-cache'
import readline from 'readline'
import fs from 'fs'
import path from 'path'

import config from './config.js'
import log, { waLogger } from './lib/logger.js'
import { setConnected, touchMessage } from './lib/keepalive.js'
import { useMongoAuthState } from './lib/mongoAuth.js'
import { getVar } from './lib/vars.js'
import { handleMessage } from './handler.js'
import { loadPlugins, middlewares, pluginCount } from './lib/pluginLoader.js'

const groupCache = new NodeCache({ stdTTL: 300, useClones: false })
const msgRetryCounterCache = new NodeCache()

/** in-memory message cache so Baileys can resend failed messages */
const messageStore = new Map()
const MAX_STORE = 3000

const ask = (q) =>
  new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
    rl.question(q, (ans) => {
      rl.close()
      resolve(ans.trim())
    })
  })

let reconnectAttempts = 0

export async function startSocket() {
  /* ------------------------- auth state ------------------------- */
  let state, saveCreds, deleteSession

  /**
   * SESSION_ID support.
   * A session generated by the web tool is base64-encoded creds.json.
   * If one is set and we are not already linked, write it to disk so the
   * bot starts already authenticated - no QR needed on the server.
   */
  if (config.sessionId) {
    const credsPath = path.join(config.sessionDir, 'creds.json')
    if (!fs.existsSync(credsPath)) {
      try {
        const raw = Buffer.from(config.sessionId.trim(), 'base64').toString('utf-8')
        const parsed = JSON.parse(raw) // fail fast if it is not real creds
        if (!parsed?.me && !parsed?.noiseKey) throw new Error('missing expected fields')
        fs.mkdirSync(config.sessionDir, { recursive: true })
        fs.writeFileSync(credsPath, raw)
        log.ok('Session restored from SESSION_ID')
      } catch (e) {
        log.error(`SESSION_ID is not valid: ${e.message}`)
        log.warn('Falling back to QR / pairing login.')
      }
    }
  }

  if (config.sessionStore === 'mongo') {
    // Namespaced per deploy: two bots on one cluster must never share creds.
    const auth = await useMongoAuthState(config.botId || 'default')
    state = auth.state
    saveCreds = auth.saveCreds
    deleteSession = auth.deleteSession
    log.info('Session store: MongoDB (survives redeploys)')
  } else {
    if (!fs.existsSync(config.sessionDir)) fs.mkdirSync(config.sessionDir, { recursive: true })
    const auth = await useMultiFileAuthState(config.sessionDir)
    state = auth.state
    saveCreds = auth.saveCreds
    deleteSession = async () => fs.rmSync(config.sessionDir, { recursive: true, force: true })
    log.info(`Session store: files (${config.sessionDir})`)
  }

  const { version, isLatest } = await fetchLatestBaileysVersion()
  log.info(`WhatsApp Web v${version.join('.')} ${isLatest ? '(latest)' : '(outdated)'}`)

  const usePairing = config.authMethod === 'pair' && !state.creds.registered

  /* -------------------------- socket -------------------------- */
  const sock = makeWASocket({
    version,
    logger: waLogger,
    auth: {
      creds: state.creds,
      keys: makeCacheableSignalKeyStore(state.keys, waLogger)
    },
    browser: usePairing ? Browsers.ubuntu('Chrome') : Browsers.macOS('Safari'),
    markOnlineOnConnect: getVar('ALWAYS_ONLINE') ?? false,
    generateHighQualityLinkPreview: true,
    syncFullHistory: false,
    msgRetryCounterCache,
    cachedGroupMetadata: async (jid) => groupCache.get(jid),
    getMessage: async (key) => messageStore.get(key.id)?.message || undefined
  })

  /* --------------------- pairing code login --------------------- */
  if (usePairing) {
    let number = config.pairNumber
    if (!number) {
      number = (await ask('\n📱 Enter your WhatsApp number (country code, no +): ')).replace(/[^0-9]/g, '')
    }
    // small delay: requesting too early makes WA reject the request
    setTimeout(async () => {
      try {
        const custom = config.pairCustomCode && /^[A-Z0-9]{8}$/.test(config.pairCustomCode)
          ? config.pairCustomCode
          : undefined
        const code = await sock.requestPairingCode(number, custom)
        const pretty = code?.match(/.{1,4}/g)?.join('-') || code
        log.banner(`
╔══════════════════════════════════════╗
║   PAIRING CODE:  ${pretty.padEnd(20)}║
╚══════════════════════════════════════╝
WhatsApp > Settings > Linked devices > Link with phone number
`)
      } catch (e) {
        log.error('Could not get a pairing code:', e.message)
      }
    }, 3000)
  }

  /* ------------------------- events ------------------------- */

  sock.ev.on('creds.update', saveCreds)

  sock.ev.on('connection.update', async (update) => {
    const { connection, lastDisconnect, qr } = update

    if (qr && !usePairing) {
      log.info('Scan this QR with WhatsApp > Linked devices:\n')
      qrcode.generate(qr, { small: true })
    }

    if (connection === 'connecting') log.info('Connecting to WhatsApp...')

    if (connection === 'open') {
      reconnectAttempts = 0
      setConnected(true)
      const me = jidNormalizedUser(sock.user?.id || '')
      log.ok(`Connected as ${sock.user?.name || 'bot'} (${me.split('@')[0]})`)
      log.ok(`${pluginCount()} plugins ready | prefix "${config.prefix}" | mode ${getVar('MODE')}`)

      if (getVar('STARTUP_MESSAGE')) {
        const owner = config.ownerNumbers[0]
        if (owner) {
          await sock
            .sendMessage(`${owner}@s.whatsapp.net`, {
              text:
                `╭━━━〔 *${config.botName}* 〕━━━╮\n` +
                `┃ ✅ Bot is online\n` +
                `┃ 🔌 Plugins: ${pluginCount()}\n` +
                `┃ ⚙️ Prefix: ${config.prefix}\n` +
                `┃ 🌐 Mode: ${getVar('MODE')}\n` +
                `┃ 📦 Version: ${config.version}\n` +
                `╰━━━━━━━━━━━━━━━━━━━╯`
            })
            .catch(() => {})
        }
      }
    }

    if (connection === 'close') {
      setConnected(false)
      const code = new Boom(lastDisconnect?.error)?.output?.statusCode
      const reason = Object.keys(DisconnectReason).find((k) => DisconnectReason[k] === code) || code

      if (code === DisconnectReason.loggedOut) {
        log.error('Logged out from WhatsApp. Clearing session - you must re-link.')
        await deleteSession()
        process.exit(0)
      }

      if (code === DisconnectReason.badSession) {
        log.error('Bad session file. Clearing session - you must re-link.')
        await deleteSession()
        process.exit(0)
      }

      // everything else is recoverable: restartRequired, timedOut, connectionLost...
      reconnectAttempts++
      const delay = Math.min(5000 * reconnectAttempts, 30_000)
      log.warn(`Connection closed (${reason}). Reconnecting in ${delay / 1000}s...`)
      setTimeout(() => startSocket().catch((e) => log.error('Reconnect failed:', e.message)), delay)
    }
  })

  /* keep group metadata cache warm - big speed win on group sends */
  sock.ev.on('groups.update', async ([event]) => {
    if (!event?.id) return
    try {
      groupCache.set(event.id, await sock.groupMetadata(event.id))
    } catch {}
  })

  sock.ev.on('group-participants.update', async (event) => {
    try {
      const metadata = await sock.groupMetadata(event.id)
      groupCache.set(event.id, metadata)
      // let plugins react to joins/leaves (welcome, goodbye, antibot)
      for (const mw of middlewares) {
        if (typeof mw.onGroupUpdate === 'function') {
          await mw.onGroupUpdate({ sock, event, metadata }).catch(() => {})
        }
      }
    } catch {}
  })

  /* incoming messages */
  sock.ev.on('messages.upsert', async ({ messages, type }) => {
    if (type !== 'notify') return
    for (const raw of messages) {
      if (!raw.message) continue
      touchMessage()
      // remember for retries + anti-delete
      messageStore.set(raw.key.id, raw)
      if (messageStore.size > MAX_STORE) {
        messageStore.delete(messageStore.keys().next().value)
      }
      await handleMessage(sock, raw, { messageStore, groupCache })
    }
  })

  /* deletions -> anti-delete plugins */
  sock.ev.on('messages.update', async (updates) => {
    for (const { key, update } of updates) {
      const isRevoke = update?.message === null || update?.messageStubType === 1

      if (isRevoke) {
        for (const mw of middlewares) {
          if (typeof mw.onDelete === 'function') {
            await mw.onDelete({ sock, key, messageStore }).catch(() => {})
          }
        }
        continue
      }

      /* edited messages arrive as an editedMessage payload */
      const edited =
        update?.message?.editedMessage?.message ||
        update?.message?.protocolMessage?.editedMessage
      if (edited) {
        for (const mw of middlewares) {
          if (typeof mw.onEdit === 'function') {
            await mw.onEdit({ sock, key, edited, messageStore }).catch(() => {})
          }
        }
      }
    }
  })

  /* incoming calls */
  sock.ev.on('call', async (calls) => {
    if (!getVar('REJECT_CALL')) return
    for (const call of calls) {
      if (call.status !== 'offer') continue
      await sock.rejectCall(call.id, call.from).catch(() => {})
      await sock
        .sendMessage(call.from, {
          text: `📵 Calls are not accepted by this bot.\nYour ${call.isVideo ? 'video' : 'voice'} call was rejected automatically.`
        })
        .catch(() => {})
    }
  })

  return sock
}

export default startSocket
